package test_generator

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func GenerateWithDefaults[T any](overrides func(*T)) T {
	var obj T
	PopulateStruct(&obj)
	if overrides != nil {
		overrides(&obj)
	}
	return obj
}

func GenerateExpected[T any](overrides func(*T)) T {
	var obj T
	PopulateStruct(&obj)
	if overrides != nil {
		overrides(&obj)
	}
	return obj
}

func RunAutoGeneratedTests[T any, R any](t *testing.T, tests []struct {
	name     string
	argsFunc func() T
	wantFunc func(args T) R
	testFunc func(args T) R
}) {
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			args := tt.argsFunc()
			want := tt.wantFunc(args)
			got := tt.testFunc(args)
			assert.Equal(t, want, got)
		})
	}
}
